### ISSUE TITLE
keeping this up-to-date?

### ISSUE THREAD

**Issue by matthewmueller** [xwb1989/sqlparser#11]
curious how much work it'd be to pull in the latest changes? seems like the vitess's parser is still under active development.

**Comment by donatj** [comment]
I'm curious this as well

**Comment by bramp** [comment]
I just submitted https://github.com/xwb1989/sqlparser/pull/18 which pulls the latest version. To be honest it took a couple of hours (because a lot has changed!). I've written instructions in the readme.md to hopefully make that easier next time.

Now just waiting for the repo owner to review and accept the pull request.

**Comment by xwb1989** [comment]
Hi @bramp , thank you for your great work! I don't have enough time to keep maintaining this repo, if you don't mind, I can transfer the ownership to you.

**Comment by bramp** [comment]
Ok this is on the latest version, and I've updated the README with instructions on how to keep it that way.
